/* Painel pessoal: os registros ficam somente neste navegador. */
const START_MONTH = 7, START_DAY = 15, END_MONTH = 8, END_DAY = 29;
const STORAGE_KEY = 'quaresma-sao-miguel-v1';
const quotes = ['Quem como Deus?','São Miguel Arcanjo, defendei-nos no combate.','Permaneça fiel até o fim.','Cada pequeno sacrifício é uma oferta de amor.','A perseverança fortalece a alma.'];
let state = JSON.parse(localStorage.getItem(STORAGE_KEY) || '{"completed":[],"theme":"dark"}');
const $ = id => document.getElementById(id);
const atMidnight = date => new Date(date.getFullYear(), date.getMonth(), date.getDate());
const dateKey = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const formatDate = date => new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'short'}).format(date).replace('.','');
function seasonFor(now){return {start:new Date(now.getFullYear(),START_MONTH,START_DAY),end:new Date(now.getFullYear(),END_MONTH,END_DAY)}}
function calendarDates(season){const dates=[];for(let date=new Date(season.start);date<=season.end;date.setDate(date.getDate()+1))dates.push(new Date(date));return dates}
function prayerDays(season){const dates=calendarDates(season),ordinary=dates.filter(date=>date.getDay()!==0);if(ordinary.length>=40)return ordinary;const finalSunday=dates.filter(date=>date.getDay()===0).at(-1);return [...ordinary,finalSunday].sort((a,b)=>a-b)}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function inCurrentSeason(key,season){return key>=dateKey(season.start)&&key<=dateKey(season.end)}
function journey(){const now=atMidnight(new Date()),season=seasonFor(now),days=prayerDays(season);if(now<season.start)return {phase:'before',daysUntil:Math.round((season.start-now)/86400000),season,days};if(now>season.end)return {phase:'after',season,days};return {phase:'during',season,days}}
function streak(season){const today=atMidnight(new Date()),pastDays=prayerDays(season).filter(date=>date<=today);let count=0;for(let i=pastDays.length-1;i>=0;i--){if(state.completed.includes(dateKey(pastDays[i])))count++;else break}return count}
function render(){const now=new Date(),today=atMidnight(now),todayKey=dateKey(now),j=journey(),total=j.days.length,done=state.completed.filter(key=>inCurrentSeason(key,j.season)),pastPrayerDays=j.days.filter(date=>date<=today),isSunday=now.getDay()===0,isCountedSunday=isSunday&&j.days.some(date=>dateKey(date)===todayKey);
  $('today-date').textContent=new Intl.DateTimeFormat('pt-BR',{day:'numeric',month:'long',year:'numeric'}).format(now);$('today-weekday').textContent=new Intl.DateTimeFormat('pt-BR',{weekday:'long'}).format(now);$('daily-quote').textContent=quotes[Math.floor((today-new Date(now.getFullYear(),0,0))/86400000)%quotes.length];
  let percent=0,remaining=total,title='Caminhada';
  if(j.phase==='before')$('journey-state').textContent=`Faltam ${j.daysUntil} dia${j.daysUntil===1?'':'s'} para começar`;
  else if(j.phase==='after'){$('journey-state').textContent='A Quaresma foi concluída. Deo gratias!';title='Jornada concluída';percent=100;remaining=0}
  else {const completedSchedule=pastPrayerDays.length;percent=Math.round((completedSchedule/total)*100);remaining=total-completedSchedule;const dayNumber=j.days.findIndex(date=>dateKey(date)===todayKey)+1;$('journey-state').textContent=isSunday&&!isCountedSunday?'Domingo da Quaresma — a oração continua.':`Dia ${dayNumber} da Quaresma${isCountedSunday?' — domingo contado.':''}`}
  $('progress-title').textContent=title;$('progress-percent').textContent=`${percent}%`;$('progress-bar').style.width=`${percent}%`;$('progress-wrap').querySelector('[role=progressbar]').setAttribute('aria-valuenow',percent);
  $('days-completed').textContent=done.length;$('days-remaining').textContent=remaining;$('stat-prayers').textContent=done.length;$('stat-penance').textContent=done.length;$('stat-remaining').textContent=remaining;$('stat-streak').textContent=streak(j.season);
  const todayDone=state.completed.includes(todayKey);$('complete-button').textContent=todayDone?'✓ Dia concluído':'✓ Cumpri hoje';$('complete-button').disabled=todayDone||(isSunday&&!isCountedSunday);$('complete-button').style.opacity=(todayDone||(isSunday&&!isCountedSunday))?.62:1;
  $('sunday-note').hidden=!isSunday;$('penance-message').textContent=isSunday?'Hoje é domingo: acolha este dia com alegria, sem esquecer da oração.':'Hoje, lembre-se de oferecer este pequeno sacrifício com amor.';
  renderCalendar(j,now);}
function renderCalendar(j,now){const calendar=$('calendar'),todayKey=dateKey(now);calendar.innerHTML='';let dayNumber=0;calendarDates(j.season).forEach(date=>{const key=dateKey(date),sunday=date.getDay()===0,countedSunday=sunday&&j.days.some(item=>dateKey(item)===key),completed=state.completed.includes(key),today=key===todayKey,future=date>atMidnight(now);if(!sunday||countedSunday)dayNumber++;let label=sunday&&!countedSunday?'✠ Domingo — oração':countedSunday?'✠ Domingo contado':completed?'✓ Concluído':today?'📍 Hoje':future?'⏳ Futuro':'○ Não marcado';const card=document.createElement('article');card.className=`day-card ${sunday?'sunday':''} ${countedSunday?'counted-sunday':''} ${completed?'completed':''} ${today?'today':''} ${future?'future':''}`;card.id=today?'dia-atual':'';card.innerHTML=`<span class="day-number">${sunday&&!countedSunday?'✠':dayNumber}</span><span class="day-date">${formatDate(date)}</span><span class="day-status">${label}</span>`;calendar.append(card)})}
function completeToday(){const j=journey(),key=dateKey(new Date()),countedSunday=j.days.some(date=>dateKey(date)===key);if(j.phase!=='during'){alert('A marcação diária fica disponível durante a Quaresma.');return}if(new Date().getDay()===0&&!countedSunday){alert('Hoje é domingo. A penitência não entra na contagem, mas a oração continua.');return}if(!state.completed.includes(key)){state.completed.push(key);save();playChime();confetti();render()}}
function confetti(){const wrap=$('confetti');for(let i=0;i<28;i++){const p=document.createElement('i');p.className='piece';p.style.left=`${Math.random()*100}%`;p.style.setProperty('--x',`${(Math.random()-.5)*220}px`);p.style.animationDelay=`${Math.random()*.3}s`;p.style.background=i%3?'var(--gold2)':'#78b5e8';wrap.append(p);setTimeout(()=>p.remove(),2100)}}
function playChime(){try{const ctx=new AudioContext(),o=ctx.createOscillator(),g=ctx.createGain();o.connect(g);g.connect(ctx.destination);o.frequency.value=660;g.gain.setValueAtTime(.035,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.4);o.start();o.stop(ctx.currentTime+.4)}catch(error){}}
function notificationText(){return new Date().getDay()===0?'Hoje é domingo. A penitência pode ser suspensa, mas não esqueça sua oração.':'Hora da sua oração da Quaresma de São Miguel Arcanjo. Não esqueça sua penitência de hoje.'}
function scheduleDailyReminder(){const now=new Date(),next=new Date();next.setHours(9,0,0,0);if(next<=now)next.setDate(next.getDate()+1);setTimeout(()=>{new Notification('Quaresma de São Miguel',{body:notificationText()});scheduleDailyReminder()},next-now)}
async function notifications(){if(!('Notification'in window)){alert('Este navegador não oferece notificações.');return}const permission=await Notification.requestPermission();if(permission==='granted'){new Notification('Quaresma de São Miguel',{body:notificationText()});$('notify-button').textContent='Lembretes ativados';localStorage.setItem('quaresma-notifications','true');scheduleDailyReminder()}else alert('Você pode permitir notificações nas configurações do navegador quando desejar.')}
function tick(){$('clock').textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
$('complete-button').addEventListener('click',completeToday);$('notify-button').addEventListener('click',notifications);$('today-button').addEventListener('click',()=>document.getElementById('dia-atual')?.scrollIntoView({behavior:'smooth',block:'center'}));$('theme-toggle').addEventListener('click',()=>{state.theme=state.theme==='light'?'dark':'light';save();applyTheme()});$('start-journey').addEventListener('click',()=>{$('welcome').hidden=true;localStorage.setItem('quaresma-welcome','seen')});
function applyTheme(){document.body.classList.toggle('light',state.theme==='light');$('theme-toggle').textContent=state.theme==='light'?'☾':'☼'}
applyTheme();if(!localStorage.getItem('quaresma-welcome'))$('welcome').hidden=false;if(localStorage.getItem('quaresma-notifications')==='true'&&Notification.permission==='granted')scheduleDailyReminder();tick();setInterval(tick,1000);render();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));
